- name: Install Kubernetes prerequisites
  ansible.builtin.package:
    name:
      # - containerd
      - docker.io
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Ensure /etc/containerd exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Configure containerd
  ansible.builtin.command: containerd config default > /etc/containerd/config.toml

- name: Restart containerd
  ansible.builtin.systemd_service:
    name: containerd
    daemon_reload: true
    enabled: true
    state: restarted

- name: Download Kubernetes release key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_release }}/deb/Release.key"
    dest: /tmp/Release.key

- name: Convert Kubernetes release key using gpg --dearmor
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    
- name: Set permissions on Kubernetes release key
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add Kubernetes apt repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_release }}/deb/ /"
    create: true
    mode: '0644'

- name: Install kubeadm, kubelet, and kubectl
  ansible.builtin.package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true
