---
- name: Download K3s Installer
  ansible.builtin.get_url:
    url: "{{ k3s_install_url }}"
    dest: /usr/local/bin/install-k3s.sh
    mode: '0755'
  when: install
  tags: 
    - install
    - k3s
    - controller
    - worker

- name: Install K3s controller
  ansible.builtin.include_tasks: controller.yaml
  when: "'controllers' in group_names"

- name: Install K3s workers
  ansible.builtin.include_tasks: worker.yaml
  when: "'workers' in group_names"
