---
- name: Download K3s Installer
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: '0755'
  when: install
  tags: 
    - install
    - k3s
    - controller
    - worker

- name: Create k3s.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: install
  delegate_to: controllers
  tags:
    - install
    - k3s
    - controller

- name: Place K3s overrides
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/k3s.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  when: install
  delegate_to: controllers
  tags:
    - install
    - k3s
    - controller

- name: Run K3s Installer
  ansible.builtin.command: /tmp/install-k3s.sh
  args:
    creates: /etc/rancher/k3s/k3s.yaml
  when: install
  delegate_to: controllers
  tags:
    - install
    - k3s
    - controller

- name: Fetch K3s Token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  when: install
  delegate_to: controllers
  tags:
    - install
    - k3s
    - controller

- name: Save K3s Token for Workers
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token['content'] | b64decode | trim }}"
  when: install
  delegate_to: controllers
  tags:
    - install
    - k3s
    - controller

- name: Uninstall K3s Controller Nodes
  ansible.builtin.command: sudo /usr/local/bin/k3s-uninstall.sh
  when: not install
  delegate_to: controllers
  tags:
    - uninstall
    - k3s
    - controller

- name: Join Worker Nodes to K3s Cluster
  ansible.builtin.command: sudo K3S_URL=https://{{ hostvars['controller0']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['controller0']['k3s_token'] }} /tmp/install-k3s.sh
  args:
    creates: /etc/rancher/k3s/k3s.yaml
  when: install
  delegate_to: workers
  tags:
    - install
    - k3s
    - worker

- name: Uninstall K3s Worker Nodes
  ansible.builtin.command: sudo /usr/local/bin/k3s-agent-uninstall.sh
  when: not install
  delegate_to: workers
  tags:
    - uninstall
    - k3s
    - worker
