- name: Join worker nodes to the Kubernetes cluster
  block:
    - name: Get the join command from the first control plane node
      ansible.builtin.command: "kubeadm token create --print-join-command"
      delegate_to: "{{ groups['control'][0] }}"
      register: join_command
      tags:
        - worker

    - debug:
        msg: "{{ join_command.stdout }}"
      tags:
        - worker

    - name: Join worker nodes to the cluster
      ansible.builtin.command: "{{ join_command.stdout }}"
      tags:
        - worker
